export const SELECT_CLIENT = 'SELECT_CLIENT';
export const SELECT_PRODUCTS = 'SELECT_PRODUCTS';
export const PRODUCTS_QUANTITY = 'PRODUCTS_QUANTITY';
export const UPDATE_TOTAL = 'UPDATE_TOTAL';
export const RESET_STATE = 'RESET_STATE';
export const ERROR_MESSAGE = 'ERROR_MESSAGE';